// 周公解梦80条经典梦境
export interface Dream {
  keyword: string;
  title: string;
  result: string;
  luck: '大吉' | '吉' | '中平' | '小凶' | '凶';
}

export const DREAMS: Dream[] = [
  { keyword:'龙', title:'梦见龙', result:'梦见龙主大吉，龙飞九天事业腾飞，龙入深海财源广进。', luck:'大吉' },
  { keyword:'鱼', title:'梦见鱼', result:'梦见鱼主有喜事，大鱼主大喜，小鱼主小喜，水中鱼主财运。', luck:'吉' },
  { keyword:'蛇', title:'梦见蛇', result:'梦见蛇主有财，蛇缠身主贵人相助，蛇蜕皮主焕然一新。', luck:'吉' },
  { keyword:'水', title:'梦见水', result:'清水主吉财运，浑水主凶口舌，洪水主大灾需防，泉水主贵人。', luck:'中平' },
  { keyword:'火', title:'梦见火', result:'大火主兴旺，小火主口舌，火烧屋主大灾，灭火主化险为夷。', luck:'中平' },
  { keyword:'飞', title:'梦见飞翔', result:'能飞主升迁，高处飞主前程远大，坠落主失利需慎。', luck:'吉' },
  { keyword:'牙齿掉落', title:'梦见掉牙', result:'主有亲人分离之忧，或主旧的去新的来，需多关心家人。', luck:'小凶' },
  { keyword:'考试', title:'梦见考试', result:'主近期压力大，通过主事事顺利，未通过主需加倍努力。', luck:'中平' },
  { keyword:'迷路', title:'梦见迷路', result:'主人生方向迷茫，需静心思考。找到出路主终能拨云见日。', luck:'小凶' },
  { keyword:'棺材', title:'梦见棺材', result:'棺主升官，材主发财。梦见棺材主升官发财大吉之兆。', luck:'大吉' },
  { keyword:'结婚', title:'梦见结婚', result:'主姻缘将至或感情和睦。单身者主桃花运旺，已婚者主幸福。', luck:'吉' },
  { keyword:'生孩子', title:'梦见生子', result:'主添丁进口，家族兴旺。男孩主事业有成，女孩主财运亨通。', luck:'大吉' },
  { keyword:'死亡', title:'梦见死亡', result:'梦死人主新生，非真凶兆。死者复生主好运，自己死亡主转运。', luck:'中平' },
  { keyword:'走路', title:'梦见走路', result:'平地走主顺利，上坡主费力但有成，下坡主需谨慎，夜路主迷茫。', luck:'中平' },
  { keyword:'骑马', title:'梦见骑马', result:'骑马主事业进展，快马加鞭主事半功倍，马失前蹄需防意外。', luck:'吉' },
  { keyword:'飞翔', title:'梦见飞行', result:'自由飞翔主心境开阔，被人追飞主压力，飞不高主受限。', luck:'吉' },
  { keyword:'下雨', title:'梦见下雨', result:'细雨主滋润好运，暴雨主口舌纷争，雨后天晴主困难消除。', luck:'中平' },
  { keyword:'下雪', title:'梦见下雪', result:'雪花飘飘主纯洁美好，大雪封路主阻碍，雪融化主困难解除。', luck:'中平' },
  { keyword:'地震', title:'梦见地震', result:'大地震动主根基动摇，需稳守当前局面，不可贸然变动。', luck:'小凶' },
  { keyword:'火灾', title:'梦见火灾', result:'大火焚屋主大凶，小火主口舌。防火防灾，谨言慎行。', luck:'凶' },
  { keyword:'车祸', title:'梦见车祸', result:'出行注意安全，近期不宜冒险。可多留神交通状况。', luck:'小凶' },
  { keyword:'落水', title:'梦见落水', result:'水深主财多难取，浅水主小麻烦。溺水主大凶需防备。', luck:'小凶' },
  { keyword:'被追', title:'梦见被追', result:'主逃避现实压力，需面对而非逃避。被追上主困难克服。', luck:'小凶' },
  { keyword:'掉牙', title:'梦见掉牙', result:'骨肉分离之象，多关心家人健康。亦主旧事终结新事开始。', luck:'小凶' },
  { keyword:'裸体', title:'梦见裸体', result:'主内心不安怕被看穿。需注意言行，保持低调。', luck:'小凶' },
  { keyword:'飞翔', title:'梦见飞翔', result:'志向高远，胸怀大志。事业将有飞跃发展。', luck:'吉' },
  { keyword:'猫', title:'梦见猫', result:'猫主灵巧智慧，梦见猫主有小财运。黑猫主防小人。', luck:'中平' },
  { keyword:'狗', title:'梦见狗', result:'狗主忠诚，梦见狗主得忠友相助。看门狗主家宅平安。', luck:'吉' },
  { keyword:'鸟', title:'梦见鸟', result:'飞鸟主自由，笼中鸟主受限。鸟儿歌唱主好消息。', luck:'吉' },
  { keyword:'蝴蝶', title:'梦见蝴蝶', result:'庄周梦蝶主虚幻。梦见蝴蝶主有浪漫之事或灵感涌现。', luck:'中平' },
  { keyword:'月亮', title:'梦见月亮', result:'月光皎洁主前途光明，月食主短暂挫折，满月主圆满。', luck:'吉' },
  { keyword:'太阳', title:'梦见太阳', result:'旭日东升主希望，烈日炎炎主压力过大，日落主收敛。', luck:'中平' },
  { keyword:'星星', title:'梦见星星', result:'繁星满天主心愿众多，摘星星主可望 achievable。', luck:'吉' },
  { keyword:'彩虹', title:'梦见彩虹', result:'彩虹主美好愿景，雨后彩虹主经历困难后见美好。', luck:'大吉' },
  { keyword:'山', title:'梦见爬山', result:'爬山主事业进取，登顶主成功，半山腰主半途而废需坚持。', luck:'吉' },
  { keyword:'树', title:'梦见大树', result:'大树参天主根基稳固，砍树主破坏，开花结果主收获。', luck:'吉' },
  { keyword:'花', title:'梦见开花', result:'花开富贵，百花齐放主喜事连连。枯萎主运势衰退。', luck:'吉' },
  { keyword:'水果', title:'梦见水果', result:'硕果累累主丰收，酸果主辛苦，甜果主喜悦。', luck:'吉' },
  { keyword:'金子', title:'梦见金子', result:'得金主财运，失金主破财。铸金主创业，熔金主消耗。', luck:'吉' },
  { keyword:'银子', title:'梦见银子', result:'白银主正财稳定，碎银主小财入账。失银需防小人。', luck:'中平' },
  { keyword:'宝石', title:'梦见宝石', result:'珍宝主稀有好运，寻宝主发现自身潜能。', luck:'大吉' },
  { keyword:'钱', title:'梦见有钱', result:'有钱花主财运亨通，捡钱主意外之财，丢钱需防破财。', luck:'吉' },
  { keyword:'借钱', title:'梦见借钱', result:'借出主帮助他人，借入主经济压力。需理财谨慎。', luck:'小凶' },
  { keyword:'搬家', title:'梦见搬家', result:'乔迁新居主环境改善，搬离旧居主告别过去。', luck:'吉' },
  { keyword:'房子', title:'梦见房子', result:'新房主新气象，旧房主怀旧，破屋需修缮。', luck:'中平' },
  { keyword:'镜子', title:'梦见镜子', result:'照镜主认识自我，镜子破碎主关系破裂，双面镜主两面性。', luck:'中平' },
  { keyword:'电话', title:'梦见打电话', result:'打通主沟通顺利，打不通主信息不畅。来电主有消息。', luck:'中平' },
  { keyword:'车', title:'梦见开车', result:'开车主掌控人生方向，堵车主阻碍，车祸主意外。', luck:'中平' },
  { keyword:'船', title:'梦见乘船', result:'顺风行船主顺利，逆水行舟主费力，翻船主大凶。', luck:'中平' },
  { keyword:'飞机', title:'梦见飞机', result:'飞行高空主视野开阔，坠机主计划受挫。', luck:'中平' },
  { keyword:'电梯', title:'梦见电梯', result:'上升主升职，下降主降级，故障主失控需小心。', luck:'中平' },
  { keyword:'门', title:'梦见开门', result:'开门见喜主新机会，关门主机遇流失，破门主强行突破。', luck:'中平' },
  { keyword:'钥匙', title:'梦见钥匙', result:'得钥匙主找到方法，丢钥匙主失去机会。', luck:'中平' },
  { keyword:'礼物', title:'梦见送礼', result:'收到礼物主得助，送出礼物主付出。惊喜礼物主好运。', luck:'吉' },
  { keyword:'食物', title:'梦见美食', result:'美食当前主满足，吃到异物主意外烦恼。饥饿主需求。', luck:'中平' },
  { keyword:'喝水', title:'梦见喝水', result:'清泉解渴主身心舒畅，污水主不良信息，口渴主需求强烈。', luck:'中平' },
  { keyword:'吃饭', title:'梦见吃饭', result:'与人共餐主和睦，独自用餐主孤独，饱食主满足。', luck:'中平' },
  { keyword:'睡觉', title:'梦见睡觉', result:'安睡主心境平和，失眠主焦虑，睡不醒主逃避现实。', luck:'中平' },
  { keyword:'怀孕', title:'梦见怀孕', result:'孕育新生命，主计划即将成型。创意项目或新开始。', luck:'吉' },
  { keyword:'旅行', title:'梦见旅行', result:'旅途愉快主顺利，迷路主方向不明，被困主受阻。', luck:'中平' },
  { keyword:'工作', title:'梦见工作', result:'工作顺利主事业有成，失业主焦虑，升职主好运。', luck:'中平' },
  { keyword:'朋友', title:'梦见朋友', result:'老友相聚主情谊，新朋友主贵人，与友争吵主口舌。', luck:'中平' },
  { keyword:'父母', title:'梦见父母', result:'父母健在主孝顺安康，父母离去主思念。多关心家人。', luck:'中平' },
  { keyword:'孩子', title:'梦见小孩', result:'孩童天真主快乐，照顾小孩主责任，走失主担忧。', luck:'中平' },
  { keyword:'老人', title:'梦见老人', result:'长者智慧主得指引，白发主长寿，跌倒主需关注健康。', luck:'中平' },
  { keyword:'敌人', title:'梦见敌人', result:'化敌为友主和解，战胜敌人主克服困难，被敌害主小人。', luck:'小凶' },
  { keyword:'鬼', title:'梦见鬼', result:'鬼神主内心恐惧，驱鬼主战胜心魔。勿信迷信，安心即可。', luck:'小凶' },
  { keyword:'坟墓', title:'梦见坟墓', result:'墓主归宿与传承，扫墓主尽孝，盗墓主损福。', luck:'小凶' },
  { keyword:'婚礼', title:'梦见婚礼', result:'红鸾星动主喜事，参加婚礼主见证幸福，缺席主错过。', luck:'吉' },
  { keyword:'葬礼', title:'梦见葬礼', result:'告别过去重新开始，非真凶兆。逝者安息生者坚强。', luck:'小凶' },
  { keyword:'雷电', title:'梦见雷电', result:'电闪雷鸣主突发变故，雨后彩虹主转机。需镇定应对。', luck:'小凶' },
  { keyword:'海啸', title:'梦见海啸', result:'巨大浪潮主情绪波动，需疏导内心。也可主大变革。', luck:'凶' },
  { keyword:'沙漠', title:'梦见沙漠', result:'荒芜之地主资源匮乏，穿越沙漠主坚持终有绿洲。', luck:'小凶' },
  { keyword:'海洋', title:'梦见大海', result:'大海浩瀚主心胸宽广，风平浪静主安宁，波涛汹涌主动荡。', luck:'中平' },
  { keyword:'森林', title:'梦见森林', result:'茂密森林主资源丰富，迷路林中主困惑，砍伐主破坏。', luck:'中平' },
];
